name: Build Artifacts - Daily
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      # Mandatory checkout action
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # Docker Hub Log In
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: docker-buildx
        uses: docker/setup-buildx-action@v3

      # Run docker build
      - name: Docker Build
        id: docker_build
        run: |
          if [ -f ./Dockerfile ]; then
            docker buildx build --platform=linux/arm64,linux/amd64 \
            -t enarciso/codex-runner:latest \
            --push \
            -f ./Dockerfile .
          else
            echo "Dockerfile is not found"
            exit 1
          fi
